name: "detection-radiodiagnosis"

networks:
  detection-radiodiagnosis-network:
    external: true

services:
  flask-detection:
    container_name: flask-detection
    build: .
    ports:
      - "5010:5010"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - detection-radiodiagnosis-network

  pinggy-detection:
    container_name: pinggy-detection
    image: pinggy/pinggy:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      - PINGGY_TOKEN=T2nRyM3PPvs
    command:
      - -p
      - "443"
      - -R0:127.0.0.1:5010
      - -o
      - StrictHostKeyChecking=no
      - -o
      - ServerAliveInterval=30
      - "T2nRyM3PPvs@ap.pro.pinggy.io"
    depends_on:
      - flask-detection
